service: aws-es-reto-img

provider:
  name: aws
  runtime: nodejs6.10
  profile: demo
  environment:
    S3_BUCKET: aws-es-reto-img
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"

functions:
  upload:
    handler: handler.upload
    events:
      - http:
            path: upload
            method: post
            cors: true

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"